#define SUPPORT_MEMORY_NOT_ALIGMENT_ACCESS
using System.Diagnostics;

public unsafe class OpCodeInfo
{
    public OpcodeEnum id;
    public string name;
    public OperandType operandType;
    public OutputType output;
    public ArgType inlineType;
    public int inlineParam;
    public byte flag;
    public OpcodeValue baseOpValue;
    public FlowType flow;
    public int constValue;

    public byte* ip;
    public uint Offset;
    public uint Token;
    public int OpCodeSize;

    public OpCodeInfo(OpcodeEnum id, string name, OperandType operandType,
        OutputType output,
        ArgType inlineType,
        int inlineParam,
        byte flag,
        OpcodeValue baseOpValue,
        FlowType flow,
        int constValue)
    {
        this.id = id;
        this.name = name;
        this.operandType = operandType;
        this.output = output;
        this.inlineType = inlineType;
        this.inlineParam = inlineParam;
        this.flag = flag;
        this.baseOpValue = baseOpValue;
        this.flow = flow;
        this.constValue = constValue;
    }

    public static unsafe OpCodeInfo DecodeOpCodeInfo(byte** ip, byte* end)
    {
        if (ip >= end)
        {
            return null;
        }

        byte c = **ip;
        if (c < (byte)OpcodeValue.PREFIX7)
        {
            return g_opcodeInfos[c];
        }
        else if (c == (byte)OpcodeValue.PREFIX1)
        {
            ++*ip;
            if (*ip >= end)
            {
                return null;
            }

            return g_opcodeInfos[(int)(**ip) + (int)OpcodeEnum.ARGLIST];
        }
        else
        {
            Debug.Assert(false, "unknown prefix");
            return null;
        }
    }

    public static unsafe int GetOpCodeSize(byte* ip, OpCodeInfo opCodeInfo)
    {
        if (opCodeInfo.inlineType != ArgType.Switch)
        {
            return 1 + opCodeInfo.inlineParam;
        }
        else
        {
            return GetI4LittleEndian(ip + 1) * 4 + 5;
        }
    }

    public unsafe float ReadSingle(int offset = 0)
    {
        return *(float*)(ip + offset);
    }

    public unsafe uint ReadUInt32(int offset = 0)
    {
        return *(uint*)(ip + offset);
    }

    public unsafe int ReadInt32(int offset = 0)
    {
        return *(int*)(ip + offset);
    }

    public unsafe long ReadInt64(int offset = 0)
    {
        return *(long*)(ip + offset);
    }

    public unsafe byte ReadInt8(int offset = 0)
    {
        return *(byte*)(ip + offset);
    }

    public unsafe sbyte ReadSInt8(int offset = 0)
    {
        return *(sbyte*)(ip + offset);
    }

    static unsafe int GetI4LittleEndian(byte* data)
    {
#if SUPPORT_MEMORY_NOT_ALIGMENT_ACCESS
        int value = (int)data;
#else
        int value = (int)data[0]
                    | ((int)data[1] << 8)
                    | ((int)data[2] << 16)
                    | ((int)data[3] << 24);
#endif
        return value;
    }

    public static OpCodeInfo[] g_opcodeInfos =
    {
        new OpCodeInfo(OpcodeEnum.NOP, "nop", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.NOP,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.BREAK, "break", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.BREAK,
            FlowType.Break, 0),
        new OpCodeInfo(OpcodeEnum.LDARG_0, "ldarg.0", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDARG_0,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDARG_1, "ldarg.1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDARG_1,
            FlowType.Next, 1),
        new OpCodeInfo(OpcodeEnum.LDARG_2, "ldarg.2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDARG_2,
            FlowType.Next, 2),
        new OpCodeInfo(OpcodeEnum.LDARG_3, "ldarg.3", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDARG_3,
            FlowType.Next, 3),
        new OpCodeInfo(OpcodeEnum.LDLOC_0, "ldloc.0", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDLOC_0,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDLOC_1, "ldloc.1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDLOC_1,
            FlowType.Next, 1),
        new OpCodeInfo(OpcodeEnum.LDLOC_2, "ldloc.2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDLOC_2,
            FlowType.Next, 2),
        new OpCodeInfo(OpcodeEnum.LDLOC_3, "ldloc.3", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDLOC_3,
            FlowType.Next, 3),
        new OpCodeInfo(OpcodeEnum.STLOC_0, "stloc.0", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STLOC_0,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STLOC_1, "stloc.1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STLOC_1,
            FlowType.Next, 1),
        new OpCodeInfo(OpcodeEnum.STLOC_2, "stloc.2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STLOC_2,
            FlowType.Next, 2),
        new OpCodeInfo(OpcodeEnum.STLOC_3, "stloc.3", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STLOC_3,
            FlowType.Next, 3),
        new OpCodeInfo(OpcodeEnum.LDARG_S, "ldarg.s", OperandType.ShortInlineVar, OutputType.None, ArgType.Data, 1, 255,
            OpcodeValue.LDARG_S,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDARGA_S, "ldarga.s", OperandType.ShortInlineVar, OutputType.None, ArgType.Data, 1,
            255,
            OpcodeValue.LDARGA_S, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STARG_S, "starg.s", OperandType.ShortInlineVar, OutputType.None, ArgType.Data, 1, 255,
            OpcodeValue.STARG_S,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDLOC_S, "ldloc.s", OperandType.ShortInlineVar, OutputType.None, ArgType.Data, 1, 255,
            OpcodeValue.LDLOC_S,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDLOCA_S, "ldloca.s", OperandType.ShortInlineVar, OutputType.None, ArgType.Data, 1,
            255,
            OpcodeValue.LDLOCA_S, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STLOC_S, "stloc.s", OperandType.ShortInlineVar, OutputType.None, ArgType.Data, 1, 255,
            OpcodeValue.STLOC_S,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDNULL, "ldnull", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDNULL,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDC_I4_M1, "ldc.i4.m1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_M1, FlowType.Next, -1),
        new OpCodeInfo(OpcodeEnum.LDC_I4_0, "ldc.i4.0", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_0, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDC_I4_1, "ldc.i4.1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_1, FlowType.Next, 1),
        new OpCodeInfo(OpcodeEnum.LDC_I4_2, "ldc.i4.2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_2, FlowType.Next, 2),
        new OpCodeInfo(OpcodeEnum.LDC_I4_3, "ldc.i4.3", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_3, FlowType.Next, 3),
        new OpCodeInfo(OpcodeEnum.LDC_I4_4, "ldc.i4.4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_4, FlowType.Next, 4),
        new OpCodeInfo(OpcodeEnum.LDC_I4_5, "ldc.i4.5", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_5, FlowType.Next, 5),
        new OpCodeInfo(OpcodeEnum.LDC_I4_6, "ldc.i4.6", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_6, FlowType.Next, 6),
        new OpCodeInfo(OpcodeEnum.LDC_I4_7, "ldc.i4.7", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_7, FlowType.Next, 7),
        new OpCodeInfo(OpcodeEnum.LDC_I4_8, "ldc.i4.8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDC_I4_8, FlowType.Next, 8),
        new OpCodeInfo(OpcodeEnum.LDC_I4_S, "ldc.i4.s", OperandType.ShortInlineI, OutputType.None, ArgType.Data, 1, 255,
            OpcodeValue.LDC_I4_S, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDC_I4, "ldc.i4", OperandType.InlineI, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDC_I4,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDC_I8, "ldc.i8", OperandType.InlineI8, OutputType.None, ArgType.Data, 8, 255,
            OpcodeValue.LDC_I8,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDC_R4, "ldc.r4", OperandType.ShortInlineR, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDC_R4,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDC_R8, "ldc.r8", OperandType.InlineR, OutputType.None, ArgType.Data, 8, 255,
            OpcodeValue.LDC_R8,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED99, "unused99", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED99, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.DUP, "dup", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.DUP,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.POP, "pop", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.POP,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.JMP, "jmp", OperandType.InlineMethod, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.JMP,
            FlowType.Call, 0),
        new OpCodeInfo(OpcodeEnum.CALL, "call", OperandType.InlineMethod, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.CALL,
            FlowType.Call, 0),
        new OpCodeInfo(OpcodeEnum.CALLI, "calli", OperandType.InlineMethod, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.CALLI,
            FlowType.Call, 0),
        new OpCodeInfo(OpcodeEnum.RET, "ret", OperandType.InlineNone, OutputType.None, ArgType.StaticBranch, 0, 255,
            OpcodeValue.RET,
            FlowType.Return, 0),
        new OpCodeInfo(OpcodeEnum.BR_S, "br.s", OperandType.ShortInlineBrTarget, OutputType.None, ArgType.BranchTarget,
            1, 255, OpcodeValue.BR_S,
            FlowType.Branch, 0),
        new OpCodeInfo(OpcodeEnum.BRFALSE_S, "brfalse.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BRFALSE_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BRTRUE_S, "brtrue.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BRTRUE_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BEQ_S, "beq.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BEQ_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGE_S, "bge.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BGE_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGT_S, "bgt.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BGT_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLE_S, "ble.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BLE_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLT_S, "blt.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BLT_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BNE_UN_S, "bne.un.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BNE_UN_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGE_UN_S, "bge.un.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BGE_UN_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGT_UN_S, "bgt.un.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BGT_UN_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLE_UN_S, "ble.un.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BLE_UN_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLT_UN_S, "blt.un.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.BLT_UN_S, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BR, "br", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget, 4, 255,
            OpcodeValue.BR,
            FlowType.Branch, 0),
        new OpCodeInfo(OpcodeEnum.BRFALSE, "brfalse", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget,
            4, 255,
            OpcodeValue.BRFALSE, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BRTRUE, "brtrue", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget,
            4, 255,
            OpcodeValue.BRTRUE, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BEQ, "beq", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget, 4, 255,
            OpcodeValue.BEQ,
            FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGE, "bge", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget, 4, 255,
            OpcodeValue.BGE,
            FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGT, "bgt", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget, 4, 255,
            OpcodeValue.BGT,
            FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLE, "ble", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget, 4, 255,
            OpcodeValue.BLE,
            FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLT, "blt", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget, 4, 255,
            OpcodeValue.BLT,
            FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BNE_UN, "bne.un", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget,
            4, 255,
            OpcodeValue.BNE_UN, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGE_UN, "bge.un", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget,
            4, 255,
            OpcodeValue.BGE_UN, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BGT_UN, "bgt.un", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget,
            4, 255,
            OpcodeValue.BGT_UN, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLE_UN, "ble.un", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget,
            4, 255,
            OpcodeValue.BLE_UN, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.BLT_UN, "blt.un", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget,
            4, 255,
            OpcodeValue.BLT_UN, FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.SWITCH, "switch", OperandType.InlineSwitch, OutputType.None, ArgType.Switch, -1, 255,
            OpcodeValue.SWITCH,
            FlowType.CondBranch, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_I1, "ldind.i1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_I1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_U1, "ldind.u1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_U1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_I2, "ldind.i2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_I2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_U2, "ldind.u2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_U2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_I4, "ldind.i4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_I4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_U4, "ldind.u4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_U4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_I8, "ldind.i8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_I8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_I, "ldind.i", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_I,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_R4, "ldind.r4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_R4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_R8, "ldind.r8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_R8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDIND_REF, "ldind.ref", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDIND_REF, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STIND_REF, "stind.ref", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_REF, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STIND_I1, "stind.i1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_I1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STIND_I2, "stind.i2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_I2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STIND_I4, "stind.i4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_I4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STIND_I8, "stind.i8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_I8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STIND_R4, "stind.r4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_R4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STIND_R8, "stind.r8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_R8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.ADD, "add", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.ADD,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.SUB, "sub", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.SUB,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.MUL, "mul", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.MUL,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.DIV, "div", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.DIV,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.DIV_UN, "div.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.DIV_UN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.REM, "rem", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.REM,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.REM_UN, "rem.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.REM_UN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.AND, "and", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.AND,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.OR, "or", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.OR, FlowType.Next,
            0),
        new OpCodeInfo(OpcodeEnum.XOR, "xor", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.XOR,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.SHL, "shl", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.SHL,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.SHR, "shr", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.SHR,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.SHR_UN, "shr.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.SHR_UN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.NEG, "neg", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.NEG,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.NOT, "not", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.NOT,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_I1, "conv.i1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_I1,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_I2, "conv.i2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_I2,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_I4, "conv.i4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_I4,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_I8, "conv.i8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_I8,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_R4, "conv.r4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_R4,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_R8, "conv.r8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_R8,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_U4, "conv.u4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_U4,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_U8, "conv.u8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_U8,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CALLVIRT, "callvirt", OperandType.InlineMethod, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.CALLVIRT, FlowType.Call, 0),
        new OpCodeInfo(OpcodeEnum.CPOBJ, "cpobj", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.CPOBJ,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDOBJ, "ldobj", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDOBJ,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDSTR, "ldstr", OperandType.InlineString, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDSTR,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.NEWOBJ, "newobj", OperandType.InlineMethod, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.NEWOBJ,
            FlowType.Call, 0),
        new OpCodeInfo(OpcodeEnum.CASTCLASS, "castclass", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.CASTCLASS, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.ISINST, "isinst", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.ISINST,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_R_UN, "conv.r.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_R_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED58, "unused58", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED58, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED1, "unused1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED1,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNBOX, "unbox", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.UNBOX,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.THROW, "throw", OperandType.InlineNone, OutputType.None, ArgType.StaticBranch, 0, 255,
            OpcodeValue.THROW, FlowType.Throw, 0),
        new OpCodeInfo(OpcodeEnum.LDFLD, "ldfld", OperandType.InlineField, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDFLD,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDFLDA, "ldflda", OperandType.InlineField, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDFLDA,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STFLD, "stfld", OperandType.InlineField, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.STFLD,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDSFLD, "ldsfld", OperandType.InlineField, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDSFLD,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDSFLDA, "ldsflda", OperandType.InlineField, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDSFLDA,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STSFLD, "stsfld", OperandType.InlineField, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.STSFLD,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STOBJ, "stobj", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.STOBJ,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I1_UN, "conv.ovf.i1.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_I1_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I2_UN, "conv.ovf.i2.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_I2_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I4_UN, "conv.ovf.i4.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_I4_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I8_UN, "conv.ovf.i8.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_I8_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U1_UN, "conv.ovf.u1.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_U1_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U2_UN, "conv.ovf.u2.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_U2_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U4_UN, "conv.ovf.u4.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_U4_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U8_UN, "conv.ovf.u8.un", OperandType.InlineNone, OutputType.None,
            ArgType.None, 0, 255,
            OpcodeValue.CONV_OVF_U8_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I_UN, "conv.ovf.i.un", OperandType.InlineNone, OutputType.None, ArgType.None,
            0, 255,
            OpcodeValue.CONV_OVF_I_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U_UN, "conv.ovf.u.un", OperandType.InlineNone, OutputType.None, ArgType.None,
            0, 255,
            OpcodeValue.CONV_OVF_U_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.BOX, "box", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.BOX,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.NEWARR, "newarr", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.NEWARR,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDLEN, "ldlen", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDLEN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEMA, "ldelema", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDELEMA,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_I1, "ldelem.i1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_I1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_U1, "ldelem.u1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_U1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_I2, "ldelem.i2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_I2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_U2, "ldelem.u2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_U2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_I4, "ldelem.i4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_I4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_U4, "ldelem.u4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_U4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_I8, "ldelem.i8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_I8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_I, "ldelem.i", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_I, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_R4, "ldelem.r4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_R4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_R8, "ldelem.r8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.LDELEM_R8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM_REF, "ldelem.ref", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.LDELEM_REF, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_I, "stelem.i", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STELEM_I, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_I1, "stelem.i1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STELEM_I1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_I2, "stelem.i2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STELEM_I2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_I4, "stelem.i4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STELEM_I4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_I8, "stelem.i8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STELEM_I8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_R4, "stelem.r4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STELEM_R4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_R8, "stelem.r8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STELEM_R8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM_REF, "stelem.ref", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.STELEM_REF, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDELEM, "ldelem", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDELEM,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STELEM, "stelem", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.STELEM,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNBOX_ANY, "unbox.any", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.UNBOX_ANY, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED5, "unused5", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED5,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED6, "unused6", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED6,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED7, "unused7", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED7,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED8, "unused8", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED8,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED9, "unused9", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED9,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED10, "unused10", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED10, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED11, "unused11", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED11, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED12, "unused12", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED12, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED13, "unused13", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED13, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED14, "unused14", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED14, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED15, "unused15", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED15, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED16, "unused16", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED16, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED17, "unused17", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED17, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I1, "conv.ovf.i1", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_I1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U1, "conv.ovf.u1", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_U1, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I2, "conv.ovf.i2", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_I2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U2, "conv.ovf.u2", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_U2, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I4, "conv.ovf.i4", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_I4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U4, "conv.ovf.u4", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_U4, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I8, "conv.ovf.i8", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_I8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U8, "conv.ovf.u8", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_U8, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED50, "unused50", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED50, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED18, "unused18", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED18, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED19, "unused19", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED19, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED20, "unused20", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED20, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED21, "unused21", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED21, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED22, "unused22", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED22, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED23, "unused23", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED23, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.REFANYVAL, "refanyval", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.REFANYVAL, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CKFINITE, "ckfinite", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CKFINITE, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED24, "unused24", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED24, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED25, "unused25", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED25, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.MKREFANY, "mkrefany", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.MKREFANY, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED59, "unused59", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED59, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED60, "unused60", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED60, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED61, "unused61", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED61, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED62, "unused62", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED62, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED63, "unused63", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED63, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED64, "unused64", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED64, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED65, "unused65", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED65, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED66, "unused66", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED66, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED67, "unused67", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED67, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDTOKEN, "ldtoken", OperandType.InlineTok, OutputType.None, ArgType.Data, 4, 255,
            OpcodeValue.LDTOKEN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_U2, "conv.u2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_U2,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_U1, "conv.u1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_U1,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_I, "conv.i", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_I,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_I, "conv.ovf.i", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_I, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_OVF_U, "conv.ovf.u", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.CONV_OVF_U, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.ADD_OVF, "add.ovf", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.ADD_OVF,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.ADD_OVF_UN, "add.ovf.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.ADD_OVF_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.MUL_OVF, "mul.ovf", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.MUL_OVF,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.MUL_OVF_UN, "mul.ovf.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.MUL_OVF_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.SUB_OVF, "sub.ovf", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.SUB_OVF,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.SUB_OVF_UN, "sub.ovf.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            255,
            OpcodeValue.SUB_OVF_UN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.ENDFINALLY, "endfinally", OperandType.InlineNone, OutputType.None,
            ArgType.StaticBranch, 0, 255,
            OpcodeValue.ENDFINALLY, FlowType.Return, 0),
        new OpCodeInfo(OpcodeEnum.LEAVE, "leave", OperandType.InlineBrTarget, OutputType.None, ArgType.BranchTarget, 4,
            255,
            OpcodeValue.LEAVE, FlowType.Branch, 0),
        new OpCodeInfo(OpcodeEnum.LEAVE_S, "leave.s", OperandType.ShortInlineBrTarget, OutputType.None,
            ArgType.BranchTarget, 1, 255,
            OpcodeValue.LEAVE_S, FlowType.Branch, 0),
        new OpCodeInfo(OpcodeEnum.STIND_I, "stind.i", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.STIND_I,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONV_U, "conv.u", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.CONV_U,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED26, "unused26", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED26, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED27, "unused27", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED27, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED28, "unused28", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED28, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED29, "unused29", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED29, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED30, "unused30", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED30, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED31, "unused31", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED31, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED32, "unused32", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED32, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED33, "unused33", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED33, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED34, "unused34", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED34, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED35, "unused35", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED35, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED36, "unused36", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED36, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED37, "unused37", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED37, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED38, "unused38", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED38, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED39, "unused39", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED39, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED40, "unused40", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED40, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED41, "unused41", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED41, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED42, "unused42", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED42, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED43, "unused43", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED43, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED44, "unused44", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED44, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED45, "unused45", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED45, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED46, "unused46", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED46, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED47, "unused47", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED47, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED48, "unused48", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.UNUSED48, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.PREFIX7, "prefix7", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIX7,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.PREFIX6, "prefix6", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIX6,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.PREFIX5, "prefix5", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIX5,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.PREFIX4, "prefix4", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIX4,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.PREFIX3, "prefix3", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIX3,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.PREFIX2, "prefix2", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIX2,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.PREFIX1, "prefix1", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIX1,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.PREFIXREF, "prefixref", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 255,
            OpcodeValue.PREFIXREF, FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.ARGLIST, "arglist", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.ARGLIST,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CEQ, "ceq", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.CEQ,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CGT, "cgt", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.CGT,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CGT_UN, "cgt.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.CGT_UN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CLT, "clt", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.CLT,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CLT_UN, "clt.un", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.CLT_UN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDFTN, "ldftn", OperandType.InlineMethod, OutputType.None, ArgType.Data, 4, 254,
            OpcodeValue.LDFTN,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDVIRTFTN, "ldvirtftn", OperandType.InlineMethod, OutputType.None, ArgType.Data, 4,
            254,
            OpcodeValue.LDVIRTFTN, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED56, "unused56", OperandType.InlineVar, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.UNUSED56, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDARG, "ldarg", OperandType.InlineVar, OutputType.None, ArgType.Data, 2, 254,
            OpcodeValue.LDARG,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDARGA, "ldarga", OperandType.InlineVar, OutputType.None, ArgType.Data, 2, 254,
            OpcodeValue.LDARGA,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STARG, "starg", OperandType.InlineVar, OutputType.None, ArgType.Data, 2, 254,
            OpcodeValue.STARG,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDLOC, "ldloc", OperandType.InlineVar, OutputType.None, ArgType.Data, 2, 254,
            OpcodeValue.LDLOC,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LDLOCA, "ldloca", OperandType.InlineVar, OutputType.None, ArgType.Data, 2, 254,
            OpcodeValue.LDLOCA,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.STLOC, "stloc", OperandType.InlineVar, OutputType.None, ArgType.Data, 2, 254,
            OpcodeValue.STLOC,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.LOCALLOC, "localloc", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.LOCALLOC, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED57, "unused57", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.UNUSED57, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.ENDFILTER, "endfilter", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.ENDFILTER, FlowType.Return, 0),
        new OpCodeInfo(OpcodeEnum.UNALIGNED_, "unaligned.", OperandType.ShortInlineI, OutputType.None, ArgType.Data, 1,
            254,
            OpcodeValue.UNALIGNED_, FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.VOLATILE_, "volatile.", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.VOLATILE_, FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.TAIL_, "tail.", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.TAIL_,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.INITOBJ, "initobj", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 254,
            OpcodeValue.INITOBJ,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.CONSTRAINED_, "constrained.", OperandType.InlineType, OutputType.None, ArgType.Data,
            4, 254,
            OpcodeValue.CONSTRAINED_, FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.CPBLK, "cpblk", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.CPBLK,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.INITBLK, "initblk", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.INITBLK,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.NO_, "no.", OperandType.ShortInlineI, OutputType.None, ArgType.Data, 1, 254,
            OpcodeValue.NO_,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.RETHROW, "rethrow", OperandType.InlineNone, OutputType.None, ArgType.StaticBranch, 0,
            254,
            OpcodeValue.RETHROW, FlowType.Throw, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED, "unused", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.UNUSED,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.SIZEOF, "sizeof", OperandType.InlineType, OutputType.None, ArgType.Data, 4, 254,
            OpcodeValue.SIZEOF,
            FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.REFANYTYPE, "refanytype", OperandType.InlineNone, OutputType.None, ArgType.None, 0,
            254,
            OpcodeValue.REFANYTYPE, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.READONLY_, "readonly.", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.READONLY_, FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED53, "unused53", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.UNUSED53, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED54, "unused54", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.UNUSED54, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED55, "unused55", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.UNUSED55, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.UNUSED70, "unused70", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 254,
            OpcodeValue.UNUSED70, FlowType.Next, 0),
        new OpCodeInfo(OpcodeEnum.ILLEGAL, "illegal", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 0,
            OpcodeValue.ILLEGAL,
            FlowType.Meta, 0),
        new OpCodeInfo(OpcodeEnum.ENDMAC, "endmac", OperandType.InlineNone, OutputType.None, ArgType.None, 0, 0,
            OpcodeValue.ENDMAC,
            FlowType.Meta, 0),
    };
}